name: "Build Android"
description: "안드로이드 빌드, 아티팩트 업로드, 슬랙으로 결과 전송"
inputs:
  build-react-native:
    description: "build react native"
    required: false
  java-distribution:
    description: "java distribution"
    required: true
  java-version:
    description: "java version"
    required: true
  android-home:
    description: "android home"
    required: false
    default: "."
  base64-keystore:
    description: "base64 keystore"
    required: true
  keystore-location:
    description: "keystore location"
    required: false
    default: "keystore"
  keystore:
    description: "keystore"
    required: false
    default: "keystore"
  keystore-properties:
    description: "keystore properties"
    required: false
    default: "keystore.properties"
  release-key-alias:
    description: "releaseKeyAlias"
    required: true
  release-key-password:
    description: "releaseKeyPassword"
    required: true
  release-store-password:
    description: "releaseStorePassword"
    required: true
  revision:
    description: "revision"
    required: false
    default: "release"
  format:
    description: "format"
    required: false
    default: "plain"
  build-properties:
    description: "build properties"
    required: false
    default: "build.properties"
  version-code:
    description: "version code"
    required: false
    default: "1"
  version-name:
    description: "version name"
    required: false
    default: "1.0.0"
  slack-token:
    description: "slack token"
    required: false
  slack-webhook-url:
    description: "slack webhook url"
    required: false
    default: "."
  slack-channel-id:
    description: "slack channel id"
    required: false
  apk-path:
    description: "apk path"
    required: false
    default: "app/build/outputs/apk/release"
  aab-path:
    description: "aab path"
    required: false
    default: "app/build/outputs/bundle/release"
  artifact-name:
    description: "artifact name"
    required: true
  artifact-path:
    description: "artifact path"
    required: false
    default: "artifacts"
runs:
  using: "composite"
  steps:
    - uses: actions/checkout@v4
    - name: yarn install
      if: ${{ inputs.build-react-native == 'true' }}
      run: yarn install
      shell: bash
    - uses: actions/setup-java@v4
      if: ${{ inputs.build-react-native != 'true' }}
      with:
        distribution: ${{ inputs.java-distribution }}
        java-version: ${{ inputs.java-version }}
        cache: "gradle"
    - uses: android-actions/setup-android@v3
      if: ${{ inputs.build-react-native != 'true' }}
    - run: |
        sudo chmod +x ${{ inputs.android-home }}/gradlew
      shell: bash
    - run: |
        echo ${{ inputs.base64-keystore }} | base64 -d > ${{ inputs.android-home }}/${{ inputs.keystore-location }}
      shell: bash
    - run: |
        echo "releaseKeyAlias=${{ inputs.release-key-alias }}" > ${{ inputs.android-home }}/${{ inputs.keystore-properties }}
        echo "releaseKeyPassword=${{ inputs.release-key-password }}" >> ${{ inputs.android-home }}/${{ inputs.keystore-properties }}
        echo "releaseKeyStore=${{ inputs.keystore }}" >> ${{ inputs.android-home }}/${{ inputs.keystore-properties }}
        echo "releaseStorePassword=${{ inputs.release-store-password }}" >> ${{ inputs.android-home }}/${{ inputs.keystore-properties }}
      shell: bash
    - run: |
        cd ${{ inputs.android-home }}
        ./gradlew androidDependencies
      if: ${{ inputs.build-react-native != 'true' }}
      shell: bash
    - run: |
        echo versionCode=${{ inputs.version-code }} >> ${{ inputs.android-home }}/${{ inputs.build-properties }}
        echo versionName=${{ inputs.version-name }} >> ${{ inputs.android-home }}/${{ inputs.build-properties }}
      shell: bash
    - run: |
        cd ${{ inputs.android-home }}
        ./gradlew assembleRelease bundleRelease
      shell: bash
    - if: ${{ inputs.slack-webhook-url != '.' }} && always()
      uses: 8398a7/action-slack@v3
      with:
        status: ${{ job.status }}
        fields: repo,message,ref # repo,message,commit,author,action,eventName,ref,workflow,job,took,pullRequest # selectable (default: repo,message)
      env:
        SLACK_WEBHOOK_URL: ${{ inputs.slack-webhook-url }}
    - name: Change File Name
      run: |
        mkdir ${{ inputs.artifact-path }}
        mv ${{ inputs.android-home }}/${{ inputs.apk-path }}/app-release.apk ${{ inputs.artifact-path }}/${{ inputs.artifact-name }}.apk
        mv ${{ inputs.android-home }}/${{ inputs.aab-path }}/app-release.aab ${{ inputs.artifact-path }}/${{ inputs.artifact-name }}.aab
      shell: bash
    - uses: actions/upload-artifact@v4
      with:
        name: ${{ inputs.artifact-name }}
        path: ${{ inputs.artifact-path }}/*.*
    - name: Slack Upload Artifacts
      if: ${{ inputs.slack-token != '' }} && {{ inputs.slack-channel-id != '' }}
      uses: MeilCli/slack-upload-file@v3
      with:
        slack_token: ${{ inputs.slack-token }}
        channel_id: ${{ inputs.slack-channel-id }}
        file_path: '${{ inputs.artifact-path }}/*.*'